name: Build Extension

on:
  push:
    branches:
      - main  # Change this to match your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Execute build script
        run: |
          chmod +x build.sh
          ./build.sh
