name: Build Extension

on:
  push:
    branches:
      - main  # Change this to match your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Build Docker Image
        run: podman build -t mtgtutor:1.0 .

      - name: Run build.sh
        run: podman run mtgtutor:1.0 ./build.sh
